-- ============================================================
--  Lotus Cinema — Oracle schema
--  Built around the existing React project (movies, bilingual,
--  manager/customer logins, favorites, seat booking, payments).
--
--  Relationship map:
--    CITIES -> CINEMAS -> HALLS -> SEATS (physical 8x12 grid)
--    MOVIES <-> GENRES            (many-to-many via MOVIE_GENRES)
--    MOVIES + HALLS -> SHOWTIMES -> SHOW_SEATS (bookable seat per show)
--    USERS -> BOOKINGS -> BOOKING_SEATS -> SHOW_SEATS
--    BOOKINGS -> PAYMENTS, BOOKINGS -> TICKETS
--    USERS <-> MOVIES via FAVORITES and via REVIEWS
--    COUPONS -> BOOKINGS
-- ============================================================

-- Drop in dependency order (safe to re-run)
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'TICKETS','PAYMENTS','BOOKING_SEATS','BOOKINGS','SHOW_SEATS','SHOWTIMES',
    'REVIEWS','FAVORITES','MOVIE_GENRES','SEATS','HALLS','CINEMAS','CITIES',
    'MOVIES','GENRES','COUPONS','USERS'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- ---------- Location ----------
CREATE TABLE cities (
  city_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name     VARCHAR2(80) NOT NULL,
  city_name_km  NVARCHAR2(80)
);

CREATE TABLE cinemas (
  cinema_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_id    NUMBER NOT NULL REFERENCES cities(city_id),
  name       VARCHAR2(120) NOT NULL,
  address    VARCHAR2(200)
);

CREATE TABLE halls (
  hall_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cinema_id  NUMBER NOT NULL REFERENCES cinemas(cinema_id),
  hall_name  VARCHAR2(60) NOT NULL,
  hall_type  VARCHAR2(20) DEFAULT 'STANDARD'   -- STANDARD / IMAX / VIP
);

-- Physical seats: 8 rows (A-H) x 12 cols = 96 per hall
CREATE TABLE seats (
  seat_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hall_id    NUMBER NOT NULL REFERENCES halls(hall_id),
  seat_row   VARCHAR2(2) NOT NULL,
  seat_col   NUMBER NOT NULL,
  seat_type  VARCHAR2(20) DEFAULT 'STANDARD',  -- STANDARD / PREMIUM / VIP
  CONSTRAINT uq_seat UNIQUE (hall_id, seat_row, seat_col)
);

-- ---------- Users (manager + customer) ----------
CREATE TABLE users (
  user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(60) NOT NULL UNIQUE,
  email         VARCHAR2(120) NOT NULL UNIQUE,
  password_hash VARCHAR2(200) NOT NULL,
  role          VARCHAR2(20) DEFAULT 'CUSTOMER' CHECK (role IN ('CUSTOMER','MANAGER')),
  full_name     VARCHAR2(120),
  phone         VARCHAR2(30),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ---------- Movies & genres ----------
CREATE TABLE movies (
  movie_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR2(200) NOT NULL,
  title_km     NVARCHAR2(200),
  tagline      VARCHAR2(300),
  overview     VARCHAR2(2000),
  release_year VARCHAR2(10),
  release_date VARCHAR2(60),
  runtime      VARCHAR2(30),
  rating       NUMBER(3,1),
  language     VARCHAR2(40) DEFAULT 'English',
  production   VARCHAR2(200),
  base_price   NUMBER(6,2) DEFAULT 6,
  poster_url   VARCHAR2(500),
  banner_url   VARCHAR2(500),
  trailer_url  VARCHAR2(500),
  status       VARCHAR2(20) DEFAULT 'NOW_SHOWING', -- NOW_SHOWING / COMING_SOON / ARCHIVED
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE genres (
  genre_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name    VARCHAR2(60) NOT NULL UNIQUE,
  genre_name_km NVARCHAR2(60)
);

CREATE TABLE movie_genres (
  movie_id NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  genre_id NUMBER NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
  CONSTRAINT pk_movie_genres PRIMARY KEY (movie_id, genre_id)
);

-- ---------- Favorites (customer <3 movie) — replaces localStorage ----------
CREATE TABLE favorites (
  user_id   NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id  NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  added_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_favorites PRIMARY KEY (user_id, movie_id)
);

-- ---------- Reviews ----------
CREATE TABLE reviews (
  review_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id   NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  stars      NUMBER(1) NOT NULL CHECK (stars BETWEEN 1 AND 5),
  review_text VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uq_review UNIQUE (user_id, movie_id)
);

CREATE INDEX ix_review_movie ON reviews(movie_id);

-- ---------- Showtimes ----------
CREATE TABLE showtimes (
  showtime_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id    NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  hall_id     NUMBER NOT NULL REFERENCES halls(hall_id),
  show_date   DATE NOT NULL,
  start_time  VARCHAR2(10) NOT NULL,   -- '18:30'
  base_price  NUMBER(6,2) NOT NULL
);

-- Each seat becomes bookable per showtime, with its own status + price
CREATE TABLE show_seats (
  show_seat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showtime_id  NUMBER NOT NULL REFERENCES showtimes(showtime_id) ON DELETE CASCADE,
  seat_id      NUMBER NOT NULL REFERENCES seats(seat_id),
  status       VARCHAR2(12) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','LOCKED','BOOKED')),
  price        NUMBER(6,2) NOT NULL,
  CONSTRAINT uq_show_seat UNIQUE (showtime_id, seat_id)
);

-- ---------- Coupons ----------
CREATE TABLE coupons (
  coupon_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR2(30) NOT NULL UNIQUE,
  discount_pct NUMBER(3) NOT NULL,
  active       NUMBER(1) DEFAULT 1
);

-- ---------- Bookings ----------
CREATE TABLE bookings (
  booking_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_ref  VARCHAR2(20) NOT NULL UNIQUE,
  user_id      NUMBER NOT NULL REFERENCES users(user_id),
  showtime_id  NUMBER NOT NULL REFERENCES showtimes(showtime_id),
  coupon_id    NUMBER REFERENCES coupons(coupon_id),
  subtotal     NUMBER(8,2) NOT NULL,
  discount     NUMBER(8,2) DEFAULT 0,
  total_price  NUMBER(8,2) NOT NULL,
  status       VARCHAR2(12) DEFAULT 'CONFIRMED' CHECK (status IN ('PENDING','CONFIRMED','CANCELLED')),
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE booking_seats (
  booking_seat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      NUMBER NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
  show_seat_id    NUMBER NOT NULL REFERENCES show_seats(show_seat_id),
  CONSTRAINT uq_booking_seat UNIQUE (show_seat_id)   -- a show-seat can be sold once
);

-- ---------- Payments ----------
CREATE TABLE payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id NUMBER NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
  method     VARCHAR2(20) NOT NULL,   -- VISA / MASTERCARD / PAYPAL / APPLEPAY / ABA / CASH
  txn_ref    VARCHAR2(40) NOT NULL,
  amount     NUMBER(8,2) NOT NULL,
  paid_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ---------- Tickets (QR per seat) ----------
CREATE TABLE tickets (
  ticket_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      NUMBER NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
  booking_seat_id NUMBER NOT NULL REFERENCES booking_seats(booking_seat_id) ON DELETE CASCADE,
  qr_code         VARCHAR2(60) NOT NULL UNIQUE,
  issued_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ---------- Indexes ----------
CREATE INDEX ix_movie_status   ON movies(status);
CREATE INDEX ix_showtime_movie ON showtimes(movie_id);
CREATE INDEX ix_showseat_show  ON show_seats(showtime_id);
CREATE INDEX ix_booking_user   ON bookings(user_id);
CREATE INDEX ix_fav_user       ON favorites(user_id);
CREATE INDEX ix_review_movie   ON reviews(movie_id);
