-- ============================================================
--  Lotus Cinema — Seed data (generated from your React project)
--  39 movies, 16 genres
-- ============================================================
SET DEFINE OFF;

-- ---------- Cities ----------
INSERT INTO cities (city_name, city_name_km) VALUES ('Phnom Penh', 'ភ្នំពេញ');
INSERT INTO cities (city_name, city_name_km) VALUES ('Siem Reap', 'សៀមរាប');

-- ---------- Cinemas ----------
INSERT INTO cinemas (city_id, name, address) VALUES (1, 'Lotus Cinema — Aeon Mall', 'Sen Sok, Phnom Penh');
INSERT INTO cinemas (city_id, name, address) VALUES (1, 'Lotus Cinema — Chip Mong', 'Chroy Changvar, Phnom Penh');
INSERT INTO cinemas (city_id, name, address) VALUES (2, 'Lotus Cinema — Siem Reap', 'Wat Bo Road, Siem Reap');

-- ---------- Halls (each cinema has a couple) ----------
INSERT INTO halls (cinema_id, hall_name, hall_type) VALUES (1, 'Hall A', 'STANDARD');
INSERT INTO halls (cinema_id, hall_name, hall_type) VALUES (1, 'Hall B (IMAX)', 'IMAX');
INSERT INTO halls (cinema_id, hall_name, hall_type) VALUES (2, 'Hall A', 'STANDARD');
INSERT INTO halls (cinema_id, hall_name, hall_type) VALUES (3, 'Hall A', 'STANDARD');

-- ---------- Genres ----------
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Action', 'សកម្មភាព');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Adventure', 'ផ្សងព្រេង');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Animation', 'គំនូរជីវចល');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Anime', 'អានីមេ');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Comedy', 'កំប្លែង');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Crime', 'ឧក្រិដ្ឋកម្ម');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Drama', 'ដ្រាម៉ា');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Fantasy', 'រវើរវាយ');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Horror', 'រន្ធត់');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Monster', 'បិសាច');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Mystery', 'អាថ៌កំបាំង');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Romance', 'ស្នេហា');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Sci-Fi', 'វិទ្យាសាស្ត្រ');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Superhero', 'វីរបុរស');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Supernatural', 'អធិធម្មជាតិ');
INSERT INTO genres (genre_name, genre_name_km) VALUES ('Thriller', 'រំភើប');

-- ---------- Users (1 manager + 2 customers; passwords are bcrypt hashes set by seed.js in demo) ----------
-- Passwords are real bcrypt hashes: manager123 / user123 / user123
INSERT INTO users (username, email, password_hash, role, full_name) VALUES ('manager', 'manager@lotus.com', '$2a$10$JWsjIVfe4xEM/m1fm3tx.e0uWSp6a6P81f0AKajKQmqjeXHxO0HPa', 'MANAGER', 'Lotus Manager');
INSERT INTO users (username, email, password_hash, role, full_name) VALUES ('sophea', 'sophea@mail.com', '$2a$10$tZTzN8bIytQAF5VJ.1osg.ug2rY2A5EZn9EUgyFShBbpB4JhIjUhy', 'CUSTOMER', 'Sophea Chan');
INSERT INTO users (username, email, password_hash, role, full_name) VALUES ('dara', 'dara@mail.com', '$2a$10$OrBu1R8w4v3FIToNt.4Ic.GNn3XKC/sky1p.Ov950F3nOGpHh3id6', 'CUSTOMER', 'Dara Kim');

-- ---------- Movies (39, straight from your project) ----------
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (1, 'Avengers: Endgame', 'អ្នកសងសឹក: ចប់ហ្គេម', 'Part of the journey is the end.', 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos'' actions.', '2019', 'April 26, 2019', '3h 2m', 8.5, 'English', 'Marvel Studios, USA', 6.5, 'https://i.pinimg.com/736x/bb/f7/0c/bbf70cc9a56b19eb7faf60bdf76bc99d.jpg', 'https://i.pinimg.com/1200x/42/00/da/4200dae9ac7b15a5c65375cbfaceaa69.jpg', 'https://www.youtube.com/embed/TcMBFSGVi1c', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (2, 'LIVIATAN RISING', 'លីវីយាតាន កើនឡើង', 'We are not alone', 'Is about the living Creature that live under the Sea since human not Already born on this Earth.', '2025', 'March 4, 2025', '1h 55m', 8, 'English', 'Warner Bros. Pictures', 7.5, 'https://i.pinimg.com/1200x/0f/6e/f5/0f6ef55b30c8bae3ac82e58a5fa95800.jpg', 'https://i.pinimg.com/1200x/fa/13/a7/fa13a76b1dd7ad8c56f28d751fdfdc91.jpg', 'https://www.youtube.com/embed/nv1_osavrq4?si=VF0LCQ71ntAl6OTs', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (3, 'TRON', 'ត្រុន', 'No going back.', 'Mankind encounters AI beings for the first time when a highly sophisticated programme, Ares, leaves the digital world for a dangerous mission in the real world.', '2025', 'October 10, 2025', '2h 5m', 8, 'English', 'Warner Bros. Pictures', 8.0, 'https://i.pinimg.com/1200x/08/c1/d3/08c1d3100061b1f6302ead6106d4910f.jpg', 'https://mouseinfo.com/wp-content/uploads/2025/04/TRON_ARES_KA_DIGITAL_1SHT_TSR_sRGB_V9-cover.jpg', 'https://www.youtube.com/embed/YShVEXb7-ic?si=yTUQckYXHFUTL-Bx', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (4, 'Marvel Zombie', NULL, 'All hero are becoming Zombie.', 'Mankind encounters AI beings for the first time when a highly sophisticated programme, Ares, leaves the digital world for a dangerous mission in the real world.', '2025', 'October 10, 2025', '2h 5m', 8, 'English', 'Warner Bros. Pictures', 8.0, 'https://i.pinimg.com/1200x/82/27/ef/8227ef1107c9484114cf49eb6b91143a.jpg', 'https://riot-us.com/wp-content/uploads/2025/09/Marvel-Zombies-Banner.jpg', 'https://www.youtube.com/embed/twHYF506-9Y?si=WCkPFgbpct00OPFF', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (5, 'Wednesday Season2', NULL, 'Wednesday new journey', 'Wednesday is a supernatural mystery series about Wednesday Addams, who attends Nevermore Academy for outcasts. The plot follows her attempts to master her psychic abilities, solve a monstrous killing spree, and uncover a supernatural mystery from her parents'' past, all while navigating new relationships at the academy. ', '2025', 'October 10, 2025', '12 Ep', 8, 'English', 'Warner Bros. Pictures', 7.5, 'https://i.pinimg.com/736x/01/ab/88/01ab8894c1bf33f4a0bb87b41c9d0839.jpg', 'https://i.pinimg.com/736x/35/a5/f1/35a5f1d758196f704d789bb4cab841b1.jpg', 'https://www.youtube.com/embed/ueCc-AYUMRs?si=yHaT1HoTPfKee4jE', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (6, 'DUNE', 'ឌូន', 'Life on the last planet', 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to a dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet''s exclusive supply of a precious resource in existence, only those who can conquer their own fear will survive. ', '2025', 'October 10, 2025', '2h 30mn', 8, 'English', 'Warner Bros. Pictures', 8.0, 'https://i.pinimg.com/736x/9a/6a/dd/9a6add70b773e23723f1bb4536417b7c.jpg', 'https://i.pinimg.com/736x/33/df/c2/33dfc2e6594d0d3be4a8b65906875537.jpg', 'https://www.youtube.com/embed/Way9Dexny3w?si=8yiICm7zEOHuTbZh', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (7, 'LOKI', NULL, 'From king of lie to King of Time', 'The Loki series has concluded, with its second season and final episode airing in 2023, although the character may return in future projects like Avengers films. The series, starring Tom Hiddleston, explored the character''s journey after Avengers ', '2023', 'October 10, 2025', '12 Ep', 8, 'English', 'Warner Bros. Pictures', 6.0, 'https://i.pinimg.com/736x/8c/b3/6f/8cb36f4cd2295e0009dcdb5c6c75905f.jpg', 'https://i.pinimg.com/736x/89/af/5c/89af5c95b09df49d9a67153fc67ac101.jpg', 'https://www.youtube.com/embed/nW948Va-l10?si=bqREFRkQfPsZZ3X5', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (8, 'ANTMAN & WARP', NULL, 'Welcome to quontim side ', 'Wednesday is a supernatural mystery series about Wednesday Addams, who attends Nevermore Academy for outcasts. The plot follows her attempts to master her psychic abilities, solve a monstrous killing spree, and uncover a supernatural mystery from her parents'' past, all while navigating new relationships at the academy. ', '2025', 'October 10, 2025', '2h 30mn', 8, 'English', 'Warner Bros. Pictures', 8.0, 'https://i.pinimg.com/1200x/c4/a0/35/c4a035685a053270fee1209e819deffd.jpg', 'https://criticscocktail.com/wp-content/uploads/2018/07/ant-man-wasp-banner-3.jpg', 'https://www.youtube.com/embed/ZlNFpri-Y40?si=x7FEDpArjE38wIF6', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (9, 'WHAT IF SEASON 2', NULL, 'Big change in Marvel World', 'What If...? Season 2 is an anthology of alternate reality stories from the Marvel Cinematic Universe, where The Watcher guides viewers through various timelines with new and familiar faces.', '2022', 'October 10, 2025', '8 Ep', 8, 'English', 'Warner Bros. Pictures', 6.0, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEhx2JuHzeqYiIUpLBJuXCH8vThK-11VvMZw&s', 'https://preview.redd.it/my-personal-review-for-what-if-season-2-v0-abukhb8ptk9c1.png?auto=webp&s=6b4c327b514a6dfdf8b1ed6eafd328935f7e8de8', 'https://www.youtube.com/embed/TiEVqZ2Bc_c?si=E4P51xEsccbd2U_F', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (10, 'WHAT IF SEASON 3', NULL, 'New version of Our hero', 'What If...? Season 3 is an anthology of alternate reality stories from the Marvel Cinematic Universe, where The Watcher guides viewers through various timelines with new and familiar faces. ', '2025', 'October 10, 2025', '8 Ep', 8, 'English', 'Warner Bros. Pictures', 7.5, 'https://preview.redd.it/new-poster-for-what-if-season-3-episode-1-what-if-the-hulk-v0-pmjv33kzhu7e1.jpeg?width=640&crop=smart&auto=webp&s=4c0624587238c0a020cb5992f061e84ee3ef34af', 'https://static0.srcdn.com/wordpress/wp-content/uploads/2024/12/what-if-season-3-mecha-avengers.jpg?w=1600&h=900&fit=crop', 'https://www.youtube.com/embed/umiKiW4En9g?si=tyRgTAncwaeF2lhZ', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (11, 'Demon Slayer: INFINITY CASTLE', NULL, 'With your blade, bring an end to the nightmare.', 'After his family is brutally murdered and his sister turned into a demon, Tanjiro Kamado joins the Demon Slayer Corps to find a cure for her. On the Mugen Train, Tanjiro and his allies face a powerful demon that threatens the lives of everyone on board.', '2025', 'October 16, 2020', '117 min', 8.2, 'Japanese', 'Ufotable, Aniplex, Shueisha', 7.5, 'https://dx35vtwkllhj9.cloudfront.net/crunchy-roll/demon-slayer-infinity-castle/images/regions/intl/onesheet.jpg', 'https://movieswetextedabout.com/wp-content/uploads/2025/09/Demon-Slayer-Infinity-Castle-Banner.jpg', 'https://www.youtube.com/embed/x7uLutVRBfI?si=I17naInANPaVuPcN', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (12, 'Thor: Ragnarok', 'ថរ: រ៉ាកណារក់', 'No hammer. No problem.', 'Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarok—the destruction of his homeworld and the end of Asgardian civilization—at the hands of the powerful and ruthless Hela.', '2017', 'November 3, 2017', '130 min', 7.9, 'English', 'Marvel Studios', 6.0, 'https://i.pinimg.com/1200x/16/5d/39/165d391974b0eabf27a3e90c12420d93.jpg', 'https://ntvb.tmsimg.com/assets/p12402331_v_h8_am.jpg?w=1280&h=720', 'https://www.youtube.com/embed/ue80QwXMRHg?si=wUUKcTDrWy2icZ7f', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (13, 'Doctor Strange in the Multiverse of Madness', NULL, 'Enter a new dimension of Strange.', 'Dr. Stephen Strange casts a forbidden spell that opens a portal to the multiverse. However, a threat emerges that may be too great for him and his team to handle, forcing him to confront alternate realities and his own darker side.', '2022', 'May 6, 2022', '126 min', 7, 'English', 'Marvel Studios', 6.0, 'https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1500x1500/products/90329/98876/doctor-strange-in-the-multiverse-of-madness-original-marvel-movie-poster-one-sheet-buy-now-at-starstills__20801.1698922344.jpg?c=2', 'https://multiverseofcolor.com/wp-content/uploads/2019/07/Doctor-Strange-2-Movie-Multiverse-Of-Madness-banner.jpg', 'https://www.youtube.com/embed/aWzlQ2N6qqg?si=0gEGym_evccZFOK4', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (14, 'Black Panther', 'ខ្លាខ្មៅ', 'Long live the king.', 'After the death of his father, T''Challa returns home to Wakanda to take his rightful place as king. When a powerful enemy reappears, T''Challa must harness the full power of the Black Panther to protect his people and secure the future of his nation.', '2018', 'February 16, 2018', '134 min', 7.3, 'English', 'Marvel Studios', 6.0, 'https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg', 'https://theknockturnal.com/wp-content/uploads/2022/11/scale.jpg', 'https://www.youtube.com/embed/xjDjIWPwcPU?si=xr-hEngoBIT7jv7i', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (15, 'Pacific Rim', 'ចំណុចប៉ាស៊ីហ្វិក', 'To fight monsters, we created monsters.', 'As monstrous creatures known as Kaiju rise from the sea to attack humanity, humans build massive robots called Jaegers to combat them. A washed-up pilot and an untested trainee are teamed up to drive a legendary Jaeger and save the world from apocalypse.', '2013', 'July 12, 2013', '131 min', 6.9, 'English', 'Legendary Pictures, Warner Bros.', 6.0, 'https://lh3.googleusercontent.com/proxy/WbUkJZDacVzPZqs-Y_4bUPSC3M1-VO8X4MBBGgmb4NGv8Br42sLuqG7BJBrh-EMqVjqUdn2CPW8VinjfS3h5NSO5PnUsvBRoqJ1x2YY', 'https://www.scannain.com/media/pacific-rim-banner.jpg', 'https://www.youtube.com/embed/Ef6vQBGqLW8?si=hI8AJeCOLcIYZyTf', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (16, 'Pacific Rim: Uprising', 'ចំណុចប៉ាស៊ីហ្វិក: កើនឡើង', 'Rise up.', 'Ten years after the Battle of the Breach, the world has changed, but the Kaiju threat returns stronger than ever. A new generation of Jaeger pilots, led by Jake Pentecost—the son of Stacker Pentecost—must unite to save humanity once again.', '2018', 'March 23, 2018', '111 min', 5.6, 'English', 'Legendary Pictures, Double Dare You Productions, Universal Pictures', 6.0, 'https://upload.wikimedia.org/wikipedia/en/1/12/Pacific_Rim_-_Uprising_%282018_film%29.jpg', 'https://www.superherohype.com/wp-content/uploads/sites/4/gallery/pacific-rim-2/pacific_rim_uprising_ver26_xlg.jpg', 'https://www.youtube.com/embed/8BAhwgjMvnM?si=rYqTJt2_SRwIb9Yh', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (17, 'John Wick: Chapter 4', 'ចន វីក: ជំពូកទី៤', 'No way back. One way out.', 'With the price on his head ever increasing, legendary hitman John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face a new enemy with powerful alliances across the globe—and forces that turn old friends into foes.', '2023', 'March 24, 2023', '169 min', 8, 'English', 'Summit Entertainment, Thunder Road Pictures, 87North Productions', 6.0, 'https://media.themoviedb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg', 'https://sm.ign.com/ign_ap/gallery/j/john-wick-/john-wick-4-the-cast-of-the-action-sequel_s323.jpg', 'https://www.youtube.com/embed/qEVUtrk8_B4?si=pECFQix2oxOsX-yq', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (18, 'Shang-Chi and the Legend of the Ten Rings', NULL, 'You can’t outrun your destiny.', 'Shang-Chi, a skilled martial artist trained since childhood to be an assassin by his father, escapes his past to live a normal life in San Francisco. But when he is drawn back into the mysterious Ten Rings organization, he must confront the legacy he thought he left behind.', '2021', 'September 3, 2021', '132 min', 7.4, 'English', 'Marvel Studios', 6.0, 'https://preview.redd.it/02ypdtot7oy71.jpg?width=640&crop=smart&auto=webp&s=4b47e34ea651d7612245410be06f1555ba1fd1ce', 'https://static0.colliderimages.com/wordpress/wp-content/uploads/2021/08/shang-chi-ending-credits-explained.jpg', 'https://www.youtube.com/embed/8YjFbMbfXaQ?si=W3VXWo_geuUZaazd', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (19, 'Moon Knight', NULL, 'Embrace the chaos.', 'Steven Grant, a mild-mannered gift shop employee, begins to experience blackouts and memories of another life. He soon discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector, who becomes the conduit for the Egyptian moon god Khonshu.', '2022', 'March 30, 2022', '45 min per episode', 7.3, 'English', 'Marvel Studios, Disney+', 6.0, 'https://cdn.marvel.com/content/1x/halfstack_busshelter_48x70_moonknight_v7_lg_0.jpg', 'https://knightedgemedia.com/wp-content/uploads/2021/11/moon-knight-teaser-trailer-banner1.jpg', 'https://www.youtube.com/embed/x7Krla_UxRg?si=RxU8QxX_mNx3oPwb', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (20, 'Superman', 'ស៊ូប៉ឺម៉ែន', 'For truth, justice and the human way.', 'After crash-landing on Earth as a baby, Kal-El is raised in Smallville as Clark Kent. As he comes into his super-powers, he must reconcile his alien Kryptonian heritage with his human upbringing, and ultimately become the iconic protector known as Superman when a new threat to humanity emerges.', '2025', 'July 11, 2025', '129 min', 7, 'English', 'DC Studios, Troll Court Entertainment, The Safran Company', 7.5, 'https://m.media-amazon.com/images/M/MV5BOGMwZGJiM2EtMzEwZC00YTYzLWIxNzYtMmJmZWNlZjgxZTMwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/078277ed-5380-4deb-b166-997beba79634/diufooh-3562c6e6-1022-46e8-9885-a8a4ff5cd02a.jpg/v1/fill/w_1469,h_544,q_70,strp/superman__2025__banner_by_crillyboy25_diufooh-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzAzNiIsInBhdGgiOiIvZi8wNzgyNzdlZC01MzgwLTRkZWItYjE2Ni05OTdiZWJhNzk2MzQvZGl1Zm9vaC0zNTYyYzZlNi0xMDIyLTQ2ZTgtOTg4NS1hOGE0ZmY1Y2QwMmEuanBnIiwid2lkdGgiOiI8PTgxOTIifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.ue5GKMIgaxfdsBIIuPvY8_c6JO41VHLvFJapPD0ANkY ', 'https://www.youtube.com/embed/Ox8ZLF6cGM0?si=51-pzZ1O-emKEGYU', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (21, 'How to Train Your Dragon', NULL, 'From fear… to friendship.', 'In a Viking village where dragons are seen as enemies, young Hiccup dreams of proving himself a true warrior. But when he befriends a mysterious Night Fury dragon, he discovers that friendship and understanding can change both their worlds forever.', '2025', 'June 13, 2025', '125 min', 8, 'English', 'DreamWorks Animation, Universal Pictures, Marc Platt Productions', 7.5, 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTLhLTo24-Thdfk9GLYhNV4Z7XgW0tldQDBjxDdF7v75EekpDZ0CWwO5bX3yN0ecYatbHQ-', 'https://dx35vtwkllhj9.cloudfront.net/universalstudios/how-to-train-your-dragon-intl/images/regions/us/share.jpg', 'https://www.youtube.com/embed/22w7z_lT6YM?si=A4qkLw0wisc5R3kE', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (22, 'Beyond Skyline', 'លើសពីផ្ទៃមេឃ', 'Survive. Fight. Evolve.', 'When alien ships invade Earth and begin abducting people, tough-as-nails Los Angeles detective Mark Corley fights to rescue his son from an alien warship. As he leads a desperate human resistance, he discovers that the key to saving humanity might lie within the aliens themselves.', '2017', 'December 15, 2017', '106 min', 5.3, 'English', 'Hydraulx Entertainment, Infinite Frameworks Studios, M45 Productions', 6.0, ' https://i0.wp.com/bloody-disgusting.com/wp-content/uploads/2017/09/beyond_skyline_ver2_xlg.jpg?resize=740%2C1097', 'https://vijayvarman.wordpress.com/wp-content/uploads/2017/10/beyond-skyline-banner-1.jpg?w=960&h=540', 'https://www.youtube.com/embed/s7UvEOzK8FQ?si=21AtYkWtxzLCwqOR', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (23, 'Solo Leveling', NULL, 'Level up or be left behind.', 'In a world where dungeons and monsters threaten humanity, weak hunter Sung Jinwoo gains the ability to level up after a near-death experience. As he grows in power, he uncovers dark secrets about the dungeons and his own origins.', '2024', 'January 7, 2024', '24 episodes (Season 1: 12 episodes, Season 2: 12 episodes)', 8.9, 'Japanese (Original), English (Dub)', 'A-1 Pictures', 7.5, 'https://i.pinimg.com/474x/79/36/da/7936dae2f934776f2e8e8f580be98317.jpg', 'https://i.ytimg.com/vi/aLBQZsj1YBE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCqL8V5Yg0kEJuNSFnj83CMFhoHbw', 'https://www.youtube.com/embed/I6JIwjWOhnQ?si=bULxmxzKTqy1-WWe', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (24, 'Battleship', 'នាវាចម្បាំង', 'The fate of the world is in their hands.', 'When alien ships threaten to destroy Earth, a fleet of naval ships led by Lieutenant Alex Hopper must defend humanity. As the aliens unleash their superior technology, Hopper and his team risk everything in a desperate fight for survival.', '2012', 'May 18, 2012', '131 min', 5.8, 'English', 'Universal Pictures, Hasbro, Roth Films', 6.0, 'https://lh3.googleusercontent.com/proxy/1vbvubeK15NIsvecVLJY1UTgmptIAUTfn0zC69OdtBRCdVN3XKKUf3Rzax54urEuJWsKFF1FlN2JpJYZ83DH_lvToxSJ-BF_hs9fKvXrAd7D', ' https://tvovermind.com/wp-content/uploads/2022/04/thumb-1920-673209-750x422.jpg', 'https://www.youtube.com/embed/JpoabtbEJOI?si=mWn9oHFBv_9_nDBT', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (25, 'Rampage', 'ការឆ្កួតឆ្កាន', 'The bigger they are, the harder they fall.', 'When a genetic experiment goes horribly wrong, three animals—an albino gorilla, a wolf, and a crocodile—mutate into massive, aggressive beasts. Primatologist Davis Okoye teams up with a genetic engineer to stop them from wreaking havoc on Chicago.', '2018', 'April 13, 2018', '107 min', 6.1, 'English', 'Warner Bros. Pictures, New Line Cinema, RatPac-Dune Entertainment', 6.0, 'https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/2876328/5956911/MOVCB51655__48142.1679600709.jpg?c=2', 'https://moviebabble.com/wp-content/uploads/2018/04/Rampage-1.jpg', 'https://www.youtube.com/embed/xeaN9kgEUJM?si=7-gipUw_enf_lS2R', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (26, 'Venom: The Last Dance', 'វេណុម: រាំចុងក្រោយ', '''Til death do they part.', 'Eddie Brock and Venom are on the run, hunted by both of their worlds. Forced into a devastating decision, they confront a cosmic threat that could end all life on Earth.', '2024', 'October 25, 2024', '97 min', 5.2, 'English', 'Sony Pictures, Marvel Entertainment, Arad Productions', 7.5, ' https://i.pinimg.com/736x/9a/46/7c/9a467c736670a8a620ddca9a6571b40b.jpg', 'https://bleedingcool.com/wp-content/uploads/2024/06/VNM3_OnLine_6072x9000_TSR_02_1349x2000_thumbnail-2000x1125.jpg', 'https://www.youtube.com/embed/D42iEo8605Y?si=YhNW0tvvuucrAu7R', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (27, 'Ne Zha', NULL, '''Destined to defy fate.''', 'Born under a demon curse, the boy Ne Zha must fight his fate and protect his people when a destructive threat rises — forging his own path from outcast to hero.', '2019', 'July 26, 2019 (China)', '110 min', 7.7, 'Mandarin (with English subtitles/dub available)', 'Chengdu Coco Cartoon, Beijing Enlight Media, Beijing Enlight Pictures', 6.0, 'https://image.tmdb.org/t/p/original/vhnxaQel1CwfcwLtCkTNpSdjte1.jpg', 'https://news.cgtn.com/news/2025-02-16/-Ne-Zha-2-captivates-North-America-audiences-including-Oscar-judges-1B2u9uI58fC/img/f5d744fe74dd422ea534078497f42197/f5d744fe74dd422ea534078497f42197.jpeg', ' https://www.youtube.com/embed/ETlOSBR92Fs?si=ArUX3Wz0E-xtvWXM', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (28, 'Jurassic World', 'ពិភពជូរ៉ាស៊ីក', '''The park is open.''', 'Twenty-two years after the events of Jurassic Park, a fully functioning dinosaur theme park—Jurassic World—on Isla Nublar has operated for years, until a new genetically modified hybrid dinosaur escapes, putting everyone in peril and forcing the park’s security chief and two children to fight for survival.', '2015', 'June 12, 2015 (US)', '124 min', 6.9, 'English', 'Universal Pictures, Amblin Entertainment, Legendary Pictures', 6.0, 'https://m.media-amazon.com/images/M/MV5BNzBhNzlkM2UtZTQyOC00NjUyLTkzMmMtNDQ1YTM5N2NmMGE5XkEyXkFqcGc@._V1_.jpg', 'https://images.squarespace-cdn.com/content/v1/54e310f0e4b0f4a6ba3ac899/1537729294782-QU0TL6K89FS9QLTNGMBT/Jurassic+Park+Fallen+Kingdom+Banner.jpg ', 'https://www.youtube.com/embed/vn9mMeWcgoM?si=CEbLxWXRJbavA549', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (29, 'Bumblebee', 'កញ្ឆឹង', '''Every hero has a beginning.''', 'On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small California beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken. When the Decepticons hunt him down, Bumblebee and Charlie team up to protect Earth and each other.', '2018', 'December 21, 2018 (USA)', '114 min', 6.8, 'English', 'Paramount Pictures, Hasbro, Tencent Pictures, Di Bonaventura Pictures', 6.0, 'https://m.media-amazon.com/images/I/91s+7+OhpxL._UF1000,1000_QL80_.jpg ', 'https://rare-gallery.com/uploads/posts/370364-4k-wallpaper.jpg ', 'https://www.youtube.com/embed/bO6qIGmwLpE?si=mLTj9cZekAidipvf', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (30, 'Jurassic World: Rebirth', 'ជូរ៉ាស៊ីកផាក: កើតជាថ្មី', '''A new era is born.''', 'Five years after the events of Jurassic World: Dominion, the planet’s ecology is largely inhospitable to dinosaurs. A covert extraction team races to an island that once housed a research facility for Jurassic Park — inhabited by the most dangerous dinosaurs left behind. :contentReference[oaicite:2]{index=2}', '2025', 'July 2, 2025 (US) :contentReference[oaicite:3]{index=3}', '133 min', 5, 'English', 'Universal Pictures, Amblin Entertainment :contentReference[oaicite:4]{index=4}', 7.5, 'https://m.media-amazon.com/images/M/MV5BMGM3ZmI3NzQtNzU5Yi00ZWI1LTg3YTAtNmNmNWIyMWFjZTBkXkEyXkFqcGc@._V1_.jpg ', 'https://4kwallpapers.com/images/wallpapers/jurassic-world-5120x2880-22719.jpg', ' https://www.youtube.com/embed/1H1Da2j2OGc?si=hfxCyt_rIesiH11q', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (31, 'Weapons', NULL, '''Every child woke up. Got out of bed. Went downstairs. Opened the front door. Walked into the dark. And they never came back.''', 'In the small town of Maybrook, 17 third-grade students mysteriously vanish at exactly 2:17 a.m. Their teacher, Justine, and a concerned father, Archer, delve into the eerie disappearance, uncovering unsettling truths that challenge their perceptions of reality.', '2025', 'August 8, 2025 (US)', '128 min', 7.5, 'English', 'New Line Cinema, Subconscious, Vertigo Entertainment, BoulderLight Pictures', 7.5, ' https://m.media-amazon.com/images/M/MV5BNTBhNWJjZWItYzY3NS00M2NkLThmOWYtYTlmNzBmN2UxZWFjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', ' https://npr.brightspotcdn.com/dims4/default/3c0ad65/2147483647/strip/true/crop/1280x720+0+0/resize/880x495!/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Ff2%2F97%2Fcc89726444d382bf8e849eb8b92d%2Fweapons-movie.jpg', 'https://www.youtube.com/embed/QKHySfXqN0I?si=HaUFi0FIauLMB-vo ', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (32, 'What If... the Watcher Disappeared?', NULL, '''When the Watcher is gone, who will protect the multiverse?''', 'In this pivotal episode, Captain Carter assembles a team of multiversal heroes, including Storm, Kahhori, and Byrdie, to rescue the Watcher, Uatu, who has been captured by a faction of Watchers. As they navigate the Fifth Dimension, they confront existential threats and uncover deeper mysteries of the multiverse.', '2024', 'December 28, 2024 (Disney+)', '30 min', 8.5, 'English', 'Marvel Studios', 7.5, 'https://preview.redd.it/1r1l7j48b2q71.jpg?width=640&crop=smart&auto=webp&s=6ba7eede860989ce77da66e1cbd32a11d18a6dcb ', 'https://images.thedirect.com/media/article_full/mcu-marvel-studios-hot-toys-vision-ultron-what-if.jpg ', 'https://www.youtube.com/embed/0tMMzqWIbcw?si=-WZjCylKckOl9l58', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (33, 'The Black Phone 2', NULL, '''Dead is just a word.''', 'Four years after surviving the Grabber''s captivity, 17-year-old Finney Blake and his sister Gwen return to confront a resurrected Grabber, now a vengeful spirit haunting Alpine Lake Youth Camp. As Gwen''s psychic abilities intensify, they uncover a disturbing family secret and battle new horrors that transcend death.', '2025', 'October 17, 2025 (USA)', '114 min', 7.2, 'English', 'Blumhouse Productions, Crooked Highway', 7.5, 'https://m.media-amazon.com/images/M/MV5BYWVkYjMxNzUtOTA1Yy00Y2UyLWExOTAtZmQ1Nzk2MTA4ZjE2XkEyXkFqcGc@._V1_.jpg', 'https://popped.blog/wp-content/uploads/2025/10/black_phone_2_mobile.jpg', 'https://www.youtube.com/embed/szKBR8NLPAk?si=5htjlh5NJAba2RrB', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (34, 'Iron Man 2', 'មនុស្សដែក ២', '''It''s not about how much we lost. It''s about how much we have left.''', 'With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman with ties to his father''s legacy. As he faces new challenges, Stark must forge new alliances and confront a powerful new enemy.', '2010', 'May 7, 2010 (USA)', '124 min', 6.9, 'English', 'Marvel Studios, Paramount Pictures', 6.0, ' https://i.pinimg.com/736x/87/13/22/871322558f56cc8df0d6d793f8991872.jpg', 'https://image.tmdb.org/t/p/original/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg ', 'https://www.youtube.com/embed/qsRZghNciIo?si=liEIb9aG8j0xCX53 ', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (35, 'Top Gun', 'កាំភ្លើងកំពូល', '''Up there with the best of the best.''', 'Hotshot pilot Pete ''Maverick'' Mitchell is sent to the U.S. Navy''s elite Fighter Weapons School, Top Gun, where he competes to be best in the class, while dealing with personal issues and a budding romance with his civilian instructor.', '1986', 'May 16, 1986', '109 min', 6.9, 'English', 'Don Simpson/Jerry Bruckheimer Films', 6.0, 'https://m.media-amazon.com/images/I/71BokibfVUL._AC_SL1500_.jpg', 'https://artofthemovies.co.uk/cdn/shop/articles/Banner_1-696896_1044x.png?v=1653437938', 'https://www.youtube.com/embed/1BJy4aHi_8I?si=-25SbgSbUKWbpS81', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (36, 'Transformers One', 'ត្រាន់ហ្វ័រមើ: មួយ', '''Witness the origin.''', 'On the planet Cybertron, miner-bots Orion Pax and D-16 are best friends who aspire to more than their station. But when they uncover a secret artifact, their bond fractures and they must face the consequences of ambition and power — ultimately becoming the legendary leaders Optimus Prime and Megatron.', '2024', 'September 20, 2024 (US)', '104 min', 7.6, 'English', 'Paramount Pictures, Paramount Animation, Hasbro Entertainment, Bayhem Films, di Bonaventura Pictures', 7.5, ' https://upload.wikimedia.org/wikipedia/en/a/a4/Transformers_One_Official_Poster.jpg', 'https://thecosmiccircus.com/wp-content/uploads/2024/09/Transformers-One-Banner.jpg ', 'https://www.youtube.com/embed/j3qqAbL6KD4?si=w_fVjEreieO26Dtu ', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (37, 'Avengers: Infinity War', 'អ្នកសងសឹក: សង្គ្រាមអនន្ត', '''An entire universe. Once and for all.''', 'As the Avengers and their allies continue to protect the world from threats too large for any one hero to handle, a new danger emerges from the cosmic shadows — Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment.', '2018', 'April 27, 2018 (USA)', '149 min', 8.4, 'English', 'Marvel Studios', 6.0, 'https://m.media-amazon.com/images/I/A1t8xCe9jwL._AC_UF894,1000_QL80_.jpg ', ' https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/846a9086-8a40-43e0-aa10-2fc7d6d73730/dc6erc1-e4a127f9-e6e8-4cc1-ae35-6b0971fd7544.png/v1/fill/w_1024,h_428,q_80,strp/avengers___infinity_war_banner___textless_by_mintmovi3_dc6erc1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NDI4IiwicGF0aCI6Ii9mLzg0NmE5MDg2LThhNDAtNDNlMC1hYTEwLTJmYzdkNmQ3MzczMC9kYzZlcmMxLWU0YTEyN2Y5LWU2ZTgtNGNjMS1hZTM1LTZiMDk3MWZkNzU0NC5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.JBaZBn7nsvK4Ylz-edrGiLwWVMdtjs5L58fz2aUZ7I8', 'https://www.youtube.com/embed/hYW8dPjSfZ8?si=lrIcQYm1dWejlJdD ', 'ARCHIVED');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (38, 'Transformers: Rise of the Beasts', 'ត្រាន់ហ្វ័រមើ: កើនឡើងសត្វ', '''Unite or fall.''', 'In the 1990s, a new faction of Transformers — the Maximals — join the Autobots as allies in the battle for Earth. When a powerful planet-eating enemy named Unicron threatens existence itself, Optimus Prime and his team must work together with the human race to protect the world from destruction.', '2023', 'June 9, 2023 (USA)', '127 min', 6, 'English', 'Paramount Pictures, Skydance, Hasbro, New Republic Pictures, Di Bonaventura Pictures', 6.0, ' https://lh4.googleusercontent.com/proxy/2JQX6gaatpLG4KP171SVPqCzEckVb9-qHMc2hx1Ggn68hHqcFJkLD5d63QZcVyawOfAsGzYyeGAGkYFu8f_GL87Zvac8B-e-r12RwquD57mwMst2VrjvDLfw53szlMIrXxw', ' https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/12/GRM_transformers-rise-beasts-web-e1702011245303.webp?resize=860%2C280&ssl=1', 'https://www.youtube.com/embed/LxWhQ1BsFYs?si=ArxKCVgPuHJCbvUw ', 'NOW_SHOWING');
INSERT INTO movies (movie_id, title, title_km, tagline, overview, release_year, release_date, runtime, rating, language, production, base_price, poster_url, banner_url, trailer_url, status) VALUES (39, 'Transformers: Dark of the Moon', 'ត្រាន់ហ្វ័រមើ: ងងឹតនៃព្រះចន្ទ', '''The war is here.''', 'The Autobots learn of a Cybertronian spacecraft hidden on the Moon and race against the Decepticons to reach it and learn its secrets. As tensions rise and the battle for Earth begins once more, Optimus Prime and his team must uncover the hidden truth of Cybertron’s final hope — and humanity’s last chance for survival.', '2011', 'June 29, 2011 (USA)', '154 min', 6.2, 'English', 'Paramount Pictures, Hasbro, Di Bonaventura Pictures, Ian Bryce Productions', 6.0, 'https://m.media-amazon.com/images/M/MV5BMTkwOTY0MTc1NV5BMl5BanBnXkFtZTcwMDQwNjA2NQ@@._V1_.jpg ', 'https://m.media-amazon.com/images/M/MV5BMTk5ODM0NTY5OF5BMl5BanBnXkFtZTcwODkyOTg5NA@@._V1_.jpg ', 'https://www.youtube.com/embed/E-Sg_zJrDxc?si=WiHxz4TaPgtdamLL ', 'ARCHIVED');

-- ---------- Movie ⇄ Genre links ----------
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (11, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (11, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (11, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (12, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (12, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (12, 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (16, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (16, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (16, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (18, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (18, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (18, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (20, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (20, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (20, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (24, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (24, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (24, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 14);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (29, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (29, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (29, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (38, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (38, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (38, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 13);

-- ---------- Coupons ----------
INSERT INTO coupons (code, discount_pct, active) VALUES ('WELCOME10', 10, 1);
INSERT INTO coupons (code, discount_pct, active) VALUES ('STUDENT20', 20, 1);
INSERT INTO coupons (code, discount_pct, active) VALUES ('LOTUS15', 15, 1);

COMMIT;

-- ============================================================
--  Generate seats for all halls + create sample showtimes
-- ============================================================
BEGIN
  gen_seats(1);
  gen_seats(2);
  gen_seats(3);
  gen_seats(4);
END;
/

-- A few showtimes across the next few days (movie_id, hall_id, date, time, base_price)
BEGIN
  create_showtime(1, 1, TRUNC(SYSDATE),   '14:00', 6);
  create_showtime(1, 2, TRUNC(SYSDATE),   '19:30', 8);
  create_showtime(2, 1, TRUNC(SYSDATE),   '17:00', 6);
  create_showtime(3, 2, TRUNC(SYSDATE)+1, '20:00', 8);
  create_showtime(4, 3, TRUNC(SYSDATE)+1, '15:30', 6);
  create_showtime(6, 1, TRUNC(SYSDATE)+2, '18:00', 7);
  create_showtime(10,4, TRUNC(SYSDATE)+2, '16:00', 6);
END;
/
COMMIT;
